services:
  db_mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'appcauldron-db_mysql'
      MYSQL_USER: 'appcauldron'
      MYSQL_PASSWORD: 'asir123'
      MYSQL_ROOT_PASSWORD: 'asir123'
    ports:
      - '3310:3306'
    expose:
      - '3310'
    volumes:
      - db_mysql-volume:/var/lib/mysql
    networks:
        network:

volumes:
  db_mysql-volume:

networks:
    network:
