services:
  netdata:
    image: netdata/netdata
#    container_name: netdata
    hostname: localhost
    ports:
    - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig-volume:/etc/netdata
      - netdatalib-volume:/var/lib/netdata
      - netdatacache-volume:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    networks:
        network:

volumes:
  netdataconfig-volume:
  netdatalib-volume:
  netdatacache-volume:

networks:
    network:
